
import java.awt.Color;



/*
 * button_txtfld.java
 *
 * Created on 08 November 2014, 10:59
 */



/**
 *
 * @author  Sunny
 */
public class button_txtfld extends javax.swing.JFrame {

    /** Creates new form button_txtfld */
    public button_txtfld() {
        initComponents();
       
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        sp1 = new javax.swing.JRadioButton();
        sp2 = new javax.swing.JRadioButton();
        sp3 = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(sp1);
        sp1.setText("Red");
        sp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sp1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(sp2);
        sp2.setText("Green");
        sp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sp2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(sp3);
        sp3.setText("Blue");
        sp3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sp3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sp3)
                    .addComponent(sp2)
                    .addComponent(sp1))
                .addContainerGap(218, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                .addGap(131, 131, 131))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(sp1)
                .addGap(36, 36, 36)
                .addComponent(sp2)
                .addGap(32, 32, 32)
                .addComponent(sp3)
                .addGap(28, 28, 28)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void sp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sp2ActionPerformed
jTextField1.setText(sp2.getText());// TODO add your handling code here:
}//GEN-LAST:event_sp2ActionPerformed

private void sp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sp1ActionPerformed
jTextField1.setText("Red");// TODO add your handling code here:
}//GEN-LAST:event_sp1ActionPerformed

private void sp3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sp3ActionPerformed
jTextField1.setBackground(Color.BLUE);// TODO add your handling code here:
}//GEN-LAST:event_sp3ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new button_txtfld().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton sp1;
    private javax.swing.JRadioButton sp2;
    private javax.swing.JRadioButton sp3;
    // End of variables declaration//GEN-END:variables

}
